# Multi-Sensor Recording System - Python Environment
# Simplified environment configuration for cross-platform compatibility

name: thermal-env

channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python - flexible version to avoid conflicts
  - python>=3.9,<3.12

  # GUI Framework  
  - pyqt=5.15.*
  
  # Computer Vision and Image Processing
  - opencv
  - pillow
  - numpy
  - scipy

  # Data Analysis and Visualization
  - matplotlib
  - pandas

  # Network Communication
  - requests
  - websockets

  # Testing Framework
  - pytest
  - pytest-cov

  # Code Quality Tools
  - flake8
  - black

  # Development Tools
  - pip

  # Pip dependencies
  - pip:
    - pytest-mock
    - pytest-qt
    - mypy
