# Multi-Sensor Recording System - Python Environment
# Updated January 2025 with latest stable compatible versions

name: thermal-env

channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python - flexible version to avoid conflicts
  - python>=3.9,<3.13

  # GUI Framework - Latest stable PyQt5
  - pyqt=5.15.*
  
  # Computer Vision and Image Processing - Latest compatible versions
  - opencv
  - pillow>=10.4.0
  - numpy>=1.26.0,<2.0.0  # Keep v1.x for OpenCV compatibility
  - scipy>=1.14.0

  # Data Analysis and Visualization
  - matplotlib>=3.10.0
  - pandas>=2.2.0

  # Network Communication
  - requests>=2.32.0
  - websockets>=13.1

  # Testing Framework - Enhanced testing stack
  - pytest>=8.4.0
  - pytest-cov>=5.0.0

  # Code Quality Tools - Latest stable
  - flake8>=7.3.0
  - black>=25.1.0

  # Development Tools
  - pip

  # Pip dependencies - Latest versions
  - pip:
    - pytest-mock>=3.14.0
    - pytest-qt>=4.4.0
    - mypy>=1.17.0
    - bandit>=1.8.0
    - memory-profiler>=0.62.0
    - psutil>=6.2.0
    - isort>=5.13.0
    - pre-commit>=4.0.0
    - sphinx>=8.1.0
    - sphinx-rtd-theme>=3.0.0
