# Milestone 5.1: Python Environment Configuration
# ===============================================
# Conda environment file for the Multi-Sensor Recording System PC Application
# This file defines all Python dependencies for consistent development environments

name: thermal-env

channels:
  - conda-forge
  - defaults
  - anaconda

dependencies:
  # Core Python
  - python=3.9

  # GUI Framework
  - pyqt5=5.15.7
  - pyqt5-tools=5.15.7.0

  # Computer Vision and Image Processing
  - opencv=4.8.0
  - pillow=10.0.0
  - numpy=1.24.3
  - scipy=1.11.1

  # Data Analysis and Visualization
  - matplotlib=3.7.2
  - pandas=2.0.3
  - pyqtgraph=0.13.3

  # Network Communication
  - requests=2.31.0
  - websockets=11.0.3
  - pyzmq=25.1.0

  # Testing Framework
  - pytest=7.4.0
  - pytest-cov=4.1.0
  - pytest-qt=4.2.0

  # Code Quality Tools
  - flake8=6.0.0
  - black=23.7.0
  - mypy=1.5.1

  # Development Tools
  - ipython=8.14.0
  - jupyter=1.0.0

  # Packaging
  - pyinstaller=5.13.0

  # System Integration
  - psutil=5.9.5
  - pyserial=3.5

  # Additional Scientific Computing
  - scikit-learn=1.3.0
  - scikit-image=0.21.0

  # Pip dependencies (packages not available via conda)
  - pip
  - pip:
    # Thermal camera specific libraries (if needed)
    - flir-python==1.0.0  # Example thermal camera SDK
    # Additional pip-only packages
    - pytest-mock==3.11.1
    - pre-commit==3.3.3
    - sphinx==7.1.2  # For documentation generation
    - sphinx-rtd-theme==1.3.0

# Environment variables
variables:
  PYTHONPATH: "${CONDA_PREFIX}/lib/python3.9/site-packages"
  QT_API: "pyqt5"
  OPENCV_LOG_LEVEL: "ERROR"

# Post-installation setup commands
# These can be run manually after environment creation:
# conda activate thermal-env
# python -m pip install --upgrade pip
# pre-commit install  # If using pre-commit hooks
